// Code generated by BobGen psql v0.0.0-20250612114253-14d7148b83cb. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model_test

import (
	"database/sql"
	"database/sql/driver"

	models "github.com/itsbbo/jadel/model"
	"github.com/oklog/ulid/v2"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor

// Make sure the type Environment runs hooks after queries
var _ bob.HookableType = &models.Environment{}

// Make sure the type Foo runs hooks after queries
var _ bob.HookableType = &models.Foo{}

// Make sure the type Migration runs hooks after queries
var _ bob.HookableType = &models.Migration{}

// Make sure the type PGStatStatement runs hooks after queries
var _ bob.HookableType = &models.PGStatStatement{}

// Make sure the type PGStatStatementsInfo runs hooks after queries
var _ bob.HookableType = &models.PGStatStatementsInfo{}

// Make sure the type PrivateKey runs hooks after queries
var _ bob.HookableType = &models.PrivateKey{}

// Make sure the type Project runs hooks after queries
var _ bob.HookableType = &models.Project{}

// Make sure the type Server runs hooks after queries
var _ bob.HookableType = &models.Server{}

// Make sure the type Session runs hooks after queries
var _ bob.HookableType = &models.Session{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &models.User{}

// Make sure the type ulid.ULID satisfies database/sql.Scanner
var _ sql.Scanner = (*ulid.ULID)(nil)

// Make sure the type ulid.ULID satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(ulid.ULID)

// Make sure the type decimal.Decimal satisfies database/sql.Scanner
var _ sql.Scanner = (*decimal.Decimal)(nil)

// Make sure the type decimal.Decimal satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(decimal.Decimal)
