// Code generated by BobGen psql v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model_test

import (
	"database/sql"
	"database/sql/driver"

	models "github.com/itsbbo/jadel/model"
	"github.com/oklog/ulid/v2"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor

// Make sure the type Migration runs hooks after queries
var _ bob.HookableType = &models.Migration{}

// Make sure the type PrivateKey runs hooks after queries
var _ bob.HookableType = &models.PrivateKey{}

// Make sure the type Project runs hooks after queries
var _ bob.HookableType = &models.Project{}

// Make sure the type Server runs hooks after queries
var _ bob.HookableType = &models.Server{}

// Make sure the type Session runs hooks after queries
var _ bob.HookableType = &models.Session{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &models.User{}

// Make sure the type ulid.ULID satisfies database/sql.Scanner
var _ sql.Scanner = (*ulid.ULID)(nil)

// Make sure the type ulid.ULID satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(ulid.ULID)

// Make sure the type pgtypes.Inet satisfies database/sql.Scanner
var _ sql.Scanner = (*pgtypes.Inet)(nil)

// Make sure the type pgtypes.Inet satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(pgtypes.Inet)
