// Code generated by BobGen psql v0.0.0-20250612114253-14d7148b83cb. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// Project is an object representing the database table.
type Project struct {
	ID          int32            `db:"id,pk" json:"id"`
	Name        string           `db:"name" json:"name"`
	Description null.Val[string] `db:"description" json:"description"`
	CreatedAt   time.Time        `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time        `db:"updated_at" json:"updated_at"`
}

// ProjectSlice is an alias for a slice of pointers to Project.
// This should almost always be used instead of []*Project.
type ProjectSlice []*Project

// Projects contains methods to work with the projects table
var Projects = psql.NewTablex[*Project, ProjectSlice, *ProjectSetter]("", "projects")

// ProjectsQuery is a query on the projects table
type ProjectsQuery = *psql.ViewQuery[*Project, ProjectSlice]

type projectColumnNames struct {
	ID          string
	Name        string
	Description string
	CreatedAt   string
	UpdatedAt   string
}

var ProjectColumns = buildProjectColumns("projects")

type projectColumns struct {
	tableAlias  string
	ID          psql.Expression
	Name        psql.Expression
	Description psql.Expression
	CreatedAt   psql.Expression
	UpdatedAt   psql.Expression
}

func (c projectColumns) Alias() string {
	return c.tableAlias
}

func (projectColumns) AliasedAs(alias string) projectColumns {
	return buildProjectColumns(alias)
}

func buildProjectColumns(alias string) projectColumns {
	return projectColumns{
		tableAlias:  alias,
		ID:          psql.Quote(alias, "id"),
		Name:        psql.Quote(alias, "name"),
		Description: psql.Quote(alias, "description"),
		CreatedAt:   psql.Quote(alias, "created_at"),
		UpdatedAt:   psql.Quote(alias, "updated_at"),
	}
}

type projectWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, int32]
	Name        psql.WhereMod[Q, string]
	Description psql.WhereNullMod[Q, string]
	CreatedAt   psql.WhereMod[Q, time.Time]
	UpdatedAt   psql.WhereMod[Q, time.Time]
}

func (projectWhere[Q]) AliasedAs(alias string) projectWhere[Q] {
	return buildProjectWhere[Q](buildProjectColumns(alias))
}

func buildProjectWhere[Q psql.Filterable](cols projectColumns) projectWhere[Q] {
	return projectWhere[Q]{
		ID:          psql.Where[Q, int32](cols.ID),
		Name:        psql.Where[Q, string](cols.Name),
		Description: psql.WhereNull[Q, string](cols.Description),
		CreatedAt:   psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:   psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

var ProjectErrors = &projectErrors{
	ErrUniqueProjectsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "projects",
		columns: []string{"id"},
		s:       "projects_pkey",
	},
}

type projectErrors struct {
	ErrUniqueProjectsPkey *UniqueConstraintError
}

// ProjectSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ProjectSetter struct {
	ID          omit.Val[int32]      `db:"id,pk" json:"id"`
	Name        omit.Val[string]     `db:"name" json:"name"`
	Description omitnull.Val[string] `db:"description" json:"description"`
	CreatedAt   omit.Val[time.Time]  `db:"created_at" json:"created_at"`
	UpdatedAt   omit.Val[time.Time]  `db:"updated_at" json:"updated_at"`
}

func (s ProjectSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsSet() {
		vals = append(vals, "id")
	}
	if s.Name.IsSet() {
		vals = append(vals, "name")
	}
	if !s.Description.IsUnset() {
		vals = append(vals, "description")
	}
	if s.CreatedAt.IsSet() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsSet() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ProjectSetter) Overwrite(t *Project) {
	if s.ID.IsSet() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsSet() {
		t.Name = s.Name.MustGet()
	}
	if !s.Description.IsUnset() {
		t.Description = s.Description.MustGetNull()
	}
	if s.CreatedAt.IsSet() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsSet() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *ProjectSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Projects.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 5)
		if s.ID.IsSet() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsSet() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if !s.Description.IsUnset() {
			vals[2] = psql.Arg(s.Description.MustGetNull())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsSet() {
			vals[3] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsSet() {
			vals[4] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ProjectSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ProjectSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsSet() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsSet() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if !s.Description.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	if s.CreatedAt.IsSet() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsSet() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindProject retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindProject(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*Project, error) {
	if len(cols) == 0 {
		return Projects.Query(
			SelectWhere.Projects.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return Projects.Query(
		SelectWhere.Projects.ID.EQ(IDPK),
		sm.Columns(Projects.Columns().Only(cols...)),
	).One(ctx, exec)
}

// ProjectExists checks the presence of a single record by primary key
func ProjectExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return Projects.Query(
		SelectWhere.Projects.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Project is retrieved from the database
func (o *Project) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Projects.AfterSelectHooks.RunHooks(ctx, exec, ProjectSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Projects.AfterInsertHooks.RunHooks(ctx, exec, ProjectSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Projects.AfterUpdateHooks.RunHooks(ctx, exec, ProjectSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Projects.AfterDeleteHooks.RunHooks(ctx, exec, ProjectSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Project
func (o *Project) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Project) pkEQ() dialect.Expression {
	return psql.Quote("projects", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Project
func (o *Project) Update(ctx context.Context, exec bob.Executor, s *ProjectSetter) error {
	v, err := Projects.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Project record with an executor
func (o *Project) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Projects.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Project using the executor
func (o *Project) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Projects.Query(
		SelectWhere.Projects.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after ProjectSlice is retrieved from the database
func (o ProjectSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Projects.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Projects.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Projects.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Projects.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ProjectSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("projects", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ProjectSlice) copyMatchingRows(from ...*Project) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ProjectSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Projects.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Project:
				o.copyMatchingRows(retrieved)
			case []*Project:
				o.copyMatchingRows(retrieved...)
			case ProjectSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Project or a slice of Project
				// then run the AfterUpdateHooks on the slice
				_, err = Projects.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ProjectSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Projects.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Project:
				o.copyMatchingRows(retrieved)
			case []*Project:
				o.copyMatchingRows(retrieved...)
			case ProjectSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Project or a slice of Project
				// then run the AfterDeleteHooks on the slice
				_, err = Projects.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ProjectSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ProjectSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Projects.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ProjectSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Projects.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ProjectSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Projects.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}
