// Code generated by BobGen psql v0.0.0-20250612114253-14d7148b83cb. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/oklog/ulid/v2"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Server is an object representing the database table.
type Server struct {
	ID           ulid.ULID        `db:"id,pk" json:"id"`
	Name         string           `db:"name" json:"name"`
	UserID       ulid.ULID        `db:"user_id" json:"user_id"`
	Description  null.Val[string] `db:"description" json:"description"`
	IP           string           `db:"ip" json:"ip"`
	Port         int32            `db:"port" json:"port"`
	Username     string           `db:"username" json:"username"`
	PrivateKeyID ulid.ULID        `db:"private_key_id" json:"private_key_id"`
	CreatedAt    time.Time        `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time        `db:"updated_at" json:"updated_at"`

	R serverR `db:"-" json:"-"`
}

// ServerSlice is an alias for a slice of pointers to Server.
// This should almost always be used instead of []*Server.
type ServerSlice []*Server

// Servers contains methods to work with the servers table
var Servers = psql.NewTablex[*Server, ServerSlice, *ServerSetter]("", "servers")

// ServersQuery is a query on the servers table
type ServersQuery = *psql.ViewQuery[*Server, ServerSlice]

// serverR is where relationships are stored.
type serverR struct {
	PrivateKey *PrivateKey `json:"PrivateKey"` // servers.servers_private_key_id_fkey
	User       *User       `json:"User"`       // servers.servers_user_id_fkey
}

type serverColumnNames struct {
	ID           string
	Name         string
	UserID       string
	Description  string
	IP           string
	Port         string
	Username     string
	PrivateKeyID string
	CreatedAt    string
	UpdatedAt    string
}

var ServerColumns = buildServerColumns("servers")

type serverColumns struct {
	tableAlias   string
	ID           psql.Expression
	Name         psql.Expression
	UserID       psql.Expression
	Description  psql.Expression
	IP           psql.Expression
	Port         psql.Expression
	Username     psql.Expression
	PrivateKeyID psql.Expression
	CreatedAt    psql.Expression
	UpdatedAt    psql.Expression
}

func (c serverColumns) Alias() string {
	return c.tableAlias
}

func (serverColumns) AliasedAs(alias string) serverColumns {
	return buildServerColumns(alias)
}

func buildServerColumns(alias string) serverColumns {
	return serverColumns{
		tableAlias:   alias,
		ID:           psql.Quote(alias, "id"),
		Name:         psql.Quote(alias, "name"),
		UserID:       psql.Quote(alias, "user_id"),
		Description:  psql.Quote(alias, "description"),
		IP:           psql.Quote(alias, "ip"),
		Port:         psql.Quote(alias, "port"),
		Username:     psql.Quote(alias, "username"),
		PrivateKeyID: psql.Quote(alias, "private_key_id"),
		CreatedAt:    psql.Quote(alias, "created_at"),
		UpdatedAt:    psql.Quote(alias, "updated_at"),
	}
}

type serverWhere[Q psql.Filterable] struct {
	ID           psql.WhereMod[Q, ulid.ULID]
	Name         psql.WhereMod[Q, string]
	UserID       psql.WhereMod[Q, ulid.ULID]
	Description  psql.WhereNullMod[Q, string]
	IP           psql.WhereMod[Q, string]
	Port         psql.WhereMod[Q, int32]
	Username     psql.WhereMod[Q, string]
	PrivateKeyID psql.WhereMod[Q, ulid.ULID]
	CreatedAt    psql.WhereMod[Q, time.Time]
	UpdatedAt    psql.WhereMod[Q, time.Time]
}

func (serverWhere[Q]) AliasedAs(alias string) serverWhere[Q] {
	return buildServerWhere[Q](buildServerColumns(alias))
}

func buildServerWhere[Q psql.Filterable](cols serverColumns) serverWhere[Q] {
	return serverWhere[Q]{
		ID:           psql.Where[Q, ulid.ULID](cols.ID),
		Name:         psql.Where[Q, string](cols.Name),
		UserID:       psql.Where[Q, ulid.ULID](cols.UserID),
		Description:  psql.WhereNull[Q, string](cols.Description),
		IP:           psql.Where[Q, string](cols.IP),
		Port:         psql.Where[Q, int32](cols.Port),
		Username:     psql.Where[Q, string](cols.Username),
		PrivateKeyID: psql.Where[Q, ulid.ULID](cols.PrivateKeyID),
		CreatedAt:    psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:    psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

var ServerErrors = &serverErrors{
	ErrUniqueServersPkey: &UniqueConstraintError{
		schema:  "",
		table:   "servers",
		columns: []string{"id"},
		s:       "servers_pkey",
	},
}

type serverErrors struct {
	ErrUniqueServersPkey *UniqueConstraintError
}

// ServerSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ServerSetter struct {
	ID           omit.Val[ulid.ULID]  `db:"id,pk" json:"id"`
	Name         omit.Val[string]     `db:"name" json:"name"`
	UserID       omit.Val[ulid.ULID]  `db:"user_id" json:"user_id"`
	Description  omitnull.Val[string] `db:"description" json:"description"`
	IP           omit.Val[string]     `db:"ip" json:"ip"`
	Port         omit.Val[int32]      `db:"port" json:"port"`
	Username     omit.Val[string]     `db:"username" json:"username"`
	PrivateKeyID omit.Val[ulid.ULID]  `db:"private_key_id" json:"private_key_id"`
	CreatedAt    omit.Val[time.Time]  `db:"created_at" json:"created_at"`
	UpdatedAt    omit.Val[time.Time]  `db:"updated_at" json:"updated_at"`
}

func (s ServerSetter) SetColumns() []string {
	vals := make([]string, 0, 10)
	if s.ID.IsSet() {
		vals = append(vals, "id")
	}
	if s.Name.IsSet() {
		vals = append(vals, "name")
	}
	if s.UserID.IsSet() {
		vals = append(vals, "user_id")
	}
	if !s.Description.IsUnset() {
		vals = append(vals, "description")
	}
	if s.IP.IsSet() {
		vals = append(vals, "ip")
	}
	if s.Port.IsSet() {
		vals = append(vals, "port")
	}
	if s.Username.IsSet() {
		vals = append(vals, "username")
	}
	if s.PrivateKeyID.IsSet() {
		vals = append(vals, "private_key_id")
	}
	if s.CreatedAt.IsSet() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsSet() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ServerSetter) Overwrite(t *Server) {
	if s.ID.IsSet() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsSet() {
		t.Name = s.Name.MustGet()
	}
	if s.UserID.IsSet() {
		t.UserID = s.UserID.MustGet()
	}
	if !s.Description.IsUnset() {
		t.Description = s.Description.MustGetNull()
	}
	if s.IP.IsSet() {
		t.IP = s.IP.MustGet()
	}
	if s.Port.IsSet() {
		t.Port = s.Port.MustGet()
	}
	if s.Username.IsSet() {
		t.Username = s.Username.MustGet()
	}
	if s.PrivateKeyID.IsSet() {
		t.PrivateKeyID = s.PrivateKeyID.MustGet()
	}
	if s.CreatedAt.IsSet() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsSet() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *ServerSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Servers.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 10)
		if s.ID.IsSet() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsSet() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsSet() {
			vals[2] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.Description.IsUnset() {
			vals[3] = psql.Arg(s.Description.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.IP.IsSet() {
			vals[4] = psql.Arg(s.IP.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Port.IsSet() {
			vals[5] = psql.Arg(s.Port.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.Username.IsSet() {
			vals[6] = psql.Arg(s.Username.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.PrivateKeyID.IsSet() {
			vals[7] = psql.Arg(s.PrivateKeyID.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsSet() {
			vals[8] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsSet() {
			vals[9] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ServerSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ServerSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 10)

	if s.ID.IsSet() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsSet() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.UserID.IsSet() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if !s.Description.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	if s.IP.IsSet() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "ip")...),
			psql.Arg(s.IP),
		}})
	}

	if s.Port.IsSet() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "port")...),
			psql.Arg(s.Port),
		}})
	}

	if s.Username.IsSet() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "username")...),
			psql.Arg(s.Username),
		}})
	}

	if s.PrivateKeyID.IsSet() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "private_key_id")...),
			psql.Arg(s.PrivateKeyID),
		}})
	}

	if s.CreatedAt.IsSet() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsSet() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindServer retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindServer(ctx context.Context, exec bob.Executor, IDPK ulid.ULID, cols ...string) (*Server, error) {
	if len(cols) == 0 {
		return Servers.Query(
			SelectWhere.Servers.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return Servers.Query(
		SelectWhere.Servers.ID.EQ(IDPK),
		sm.Columns(Servers.Columns().Only(cols...)),
	).One(ctx, exec)
}

// ServerExists checks the presence of a single record by primary key
func ServerExists(ctx context.Context, exec bob.Executor, IDPK ulid.ULID) (bool, error) {
	return Servers.Query(
		SelectWhere.Servers.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Server is retrieved from the database
func (o *Server) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Servers.AfterSelectHooks.RunHooks(ctx, exec, ServerSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Servers.AfterInsertHooks.RunHooks(ctx, exec, ServerSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Servers.AfterUpdateHooks.RunHooks(ctx, exec, ServerSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Servers.AfterDeleteHooks.RunHooks(ctx, exec, ServerSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Server
func (o *Server) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Server) pkEQ() dialect.Expression {
	return psql.Quote("servers", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Server
func (o *Server) Update(ctx context.Context, exec bob.Executor, s *ServerSetter) error {
	v, err := Servers.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Server record with an executor
func (o *Server) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Servers.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Server using the executor
func (o *Server) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Servers.Query(
		SelectWhere.Servers.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ServerSlice is retrieved from the database
func (o ServerSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Servers.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Servers.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Servers.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Servers.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ServerSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("servers", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ServerSlice) copyMatchingRows(from ...*Server) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ServerSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Servers.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Server:
				o.copyMatchingRows(retrieved)
			case []*Server:
				o.copyMatchingRows(retrieved...)
			case ServerSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Server or a slice of Server
				// then run the AfterUpdateHooks on the slice
				_, err = Servers.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ServerSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Servers.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Server:
				o.copyMatchingRows(retrieved)
			case []*Server:
				o.copyMatchingRows(retrieved...)
			case ServerSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Server or a slice of Server
				// then run the AfterDeleteHooks on the slice
				_, err = Servers.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ServerSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ServerSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Servers.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ServerSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Servers.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ServerSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Servers.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type serverJoins[Q dialect.Joinable] struct {
	typ        string
	PrivateKey modAs[Q, privateKeyColumns]
	User       modAs[Q, userColumns]
}

func (j serverJoins[Q]) aliasedAs(alias string) serverJoins[Q] {
	return buildServerJoins[Q](buildServerColumns(alias), j.typ)
}

func buildServerJoins[Q dialect.Joinable](cols serverColumns, typ string) serverJoins[Q] {
	return serverJoins[Q]{
		typ: typ,
		PrivateKey: modAs[Q, privateKeyColumns]{
			c: PrivateKeyColumns,
			f: func(to privateKeyColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, PrivateKeys.Name().As(to.Alias())).On(
						to.ID.EQ(cols.PrivateKeyID),
					))
				}

				return mods
			},
		},
		User: modAs[Q, userColumns]{
			c: UserColumns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}

// PrivateKey starts a query for related objects on private_keys
func (o *Server) PrivateKey(mods ...bob.Mod[*dialect.SelectQuery]) PrivateKeysQuery {
	return PrivateKeys.Query(append(mods,
		sm.Where(PrivateKeyColumns.ID.EQ(psql.Arg(o.PrivateKeyID))),
	)...)
}

func (os ServerSlice) PrivateKey(mods ...bob.Mod[*dialect.SelectQuery]) PrivateKeysQuery {
	pkPrivateKeyID := make(pgtypes.Array[ulid.ULID], len(os))
	for i, o := range os {
		pkPrivateKeyID[i] = o.PrivateKeyID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkPrivateKeyID), "bytea[]")),
	))

	return PrivateKeys.Query(append(mods,
		sm.Where(psql.Group(PrivateKeyColumns.ID).OP("IN", PKArgExpr)),
	)...)
}

// User starts a query for related objects on users
func (o *Server) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(UserColumns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os ServerSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[ulid.ULID], len(os))
	for i, o := range os {
		pkUserID[i] = o.UserID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "bytea[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(UserColumns.ID).OP("IN", PKArgExpr)),
	)...)
}

func (o *Server) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "PrivateKey":
		rel, ok := retrieved.(*PrivateKey)
		if !ok {
			return fmt.Errorf("server cannot load %T as %q", retrieved, name)
		}

		o.R.PrivateKey = rel

		if rel != nil {
			rel.R.Servers = ServerSlice{o}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("server cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Servers = ServerSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("server has no relationship %q", name)
	}
}

type serverPreloader struct {
	PrivateKey func(...psql.PreloadOption) psql.Preloader
	User       func(...psql.PreloadOption) psql.Preloader
}

func buildServerPreloader() serverPreloader {
	return serverPreloader{
		PrivateKey: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*PrivateKey, PrivateKeySlice](orm.Relationship{
				Name: "PrivateKey",
				Sides: []orm.RelSide{
					{
						From: TableNames.Servers,
						To:   TableNames.PrivateKeys,
						FromColumns: []string{
							ColumnNames.Servers.PrivateKeyID,
						},
						ToColumns: []string{
							ColumnNames.PrivateKeys.ID,
						},
					},
				},
			}, PrivateKeys.Columns().Names(), opts...)
		},
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](orm.Relationship{
				Name: "User",
				Sides: []orm.RelSide{
					{
						From: TableNames.Servers,
						To:   TableNames.Users,
						FromColumns: []string{
							ColumnNames.Servers.UserID,
						},
						ToColumns: []string{
							ColumnNames.Users.ID,
						},
					},
				},
			}, Users.Columns().Names(), opts...)
		},
	}
}

type serverThenLoader[Q orm.Loadable] struct {
	PrivateKey func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	User       func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildServerThenLoader[Q orm.Loadable]() serverThenLoader[Q] {
	type PrivateKeyLoadInterface interface {
		LoadPrivateKey(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return serverThenLoader[Q]{
		PrivateKey: thenLoadBuilder[Q](
			"PrivateKey",
			func(ctx context.Context, exec bob.Executor, retrieved PrivateKeyLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadPrivateKey(ctx, exec, mods...)
			},
		),
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadPrivateKey loads the server's PrivateKey into the .R struct
func (o *Server) LoadPrivateKey(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.PrivateKey = nil

	related, err := o.PrivateKey(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Servers = ServerSlice{o}

	o.R.PrivateKey = related
	return nil
}

// LoadPrivateKey loads the server's PrivateKey into the .R struct
func (os ServerSlice) LoadPrivateKey(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	privateKeys, err := os.PrivateKey(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range privateKeys {
			if o.PrivateKeyID != rel.ID {
				continue
			}

			rel.R.Servers = append(rel.R.Servers, o)

			o.R.PrivateKey = rel
			break
		}
	}

	return nil
}

// LoadUser loads the server's User into the .R struct
func (o *Server) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Servers = ServerSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the server's User into the .R struct
func (os ServerSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range users {
			if o.UserID != rel.ID {
				continue
			}

			rel.R.Servers = append(rel.R.Servers, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

func attachServerPrivateKey0(ctx context.Context, exec bob.Executor, count int, server0 *Server, privateKey1 *PrivateKey) (*Server, error) {
	setter := &ServerSetter{
		PrivateKeyID: omit.From(privateKey1.ID),
	}

	err := server0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachServerPrivateKey0: %w", err)
	}

	return server0, nil
}

func (server0 *Server) InsertPrivateKey(ctx context.Context, exec bob.Executor, related *PrivateKeySetter) error {
	privateKey1, err := PrivateKeys.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachServerPrivateKey0(ctx, exec, 1, server0, privateKey1)
	if err != nil {
		return err
	}

	server0.R.PrivateKey = privateKey1

	privateKey1.R.Servers = append(privateKey1.R.Servers, server0)

	return nil
}

func (server0 *Server) AttachPrivateKey(ctx context.Context, exec bob.Executor, privateKey1 *PrivateKey) error {
	var err error

	_, err = attachServerPrivateKey0(ctx, exec, 1, server0, privateKey1)
	if err != nil {
		return err
	}

	server0.R.PrivateKey = privateKey1

	privateKey1.R.Servers = append(privateKey1.R.Servers, server0)

	return nil
}

func attachServerUser0(ctx context.Context, exec bob.Executor, count int, server0 *Server, user1 *User) (*Server, error) {
	setter := &ServerSetter{
		UserID: omit.From(user1.ID),
	}

	err := server0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachServerUser0: %w", err)
	}

	return server0, nil
}

func (server0 *Server) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachServerUser0(ctx, exec, 1, server0, user1)
	if err != nil {
		return err
	}

	server0.R.User = user1

	user1.R.Servers = append(user1.R.Servers, server0)

	return nil
}

func (server0 *Server) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachServerUser0(ctx, exec, 1, server0, user1)
	if err != nil {
		return err
	}

	server0.R.User = user1

	user1.R.Servers = append(user1.R.Servers, server0)

	return nil
}
