// Code generated by BobGen psql v0.0.0-20250612114253-14d7148b83cb. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/oklog/ulid/v2"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Session is an object representing the database table.
type Session struct {
	ID        string           `db:"id,pk" json:"id"`
	UserID    ulid.ULID        `db:"user_id" json:"user_id"`
	IPAddress null.Val[string] `db:"ip_address" json:"ip_address"`
	UserAgent null.Val[string] `db:"user_agent" json:"user_agent"`
	ExpiredAt time.Time        `db:"expired_at" json:"expired_at"`

	R sessionR `db:"-" json:"-"`
}

// SessionSlice is an alias for a slice of pointers to Session.
// This should almost always be used instead of []*Session.
type SessionSlice []*Session

// Sessions contains methods to work with the sessions table
var Sessions = psql.NewTablex[*Session, SessionSlice, *SessionSetter]("", "sessions")

// SessionsQuery is a query on the sessions table
type SessionsQuery = *psql.ViewQuery[*Session, SessionSlice]

// sessionR is where relationships are stored.
type sessionR struct {
	User *User `json:"User"` // sessions.sessions_user_id_fkey
}

type sessionColumnNames struct {
	ID        string
	UserID    string
	IPAddress string
	UserAgent string
	ExpiredAt string
}

var SessionColumns = buildSessionColumns("sessions")

type sessionColumns struct {
	tableAlias string
	ID         psql.Expression
	UserID     psql.Expression
	IPAddress  psql.Expression
	UserAgent  psql.Expression
	ExpiredAt  psql.Expression
}

func (c sessionColumns) Alias() string {
	return c.tableAlias
}

func (sessionColumns) AliasedAs(alias string) sessionColumns {
	return buildSessionColumns(alias)
}

func buildSessionColumns(alias string) sessionColumns {
	return sessionColumns{
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		UserID:     psql.Quote(alias, "user_id"),
		IPAddress:  psql.Quote(alias, "ip_address"),
		UserAgent:  psql.Quote(alias, "user_agent"),
		ExpiredAt:  psql.Quote(alias, "expired_at"),
	}
}

type sessionWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, string]
	UserID    psql.WhereMod[Q, ulid.ULID]
	IPAddress psql.WhereNullMod[Q, string]
	UserAgent psql.WhereNullMod[Q, string]
	ExpiredAt psql.WhereMod[Q, time.Time]
}

func (sessionWhere[Q]) AliasedAs(alias string) sessionWhere[Q] {
	return buildSessionWhere[Q](buildSessionColumns(alias))
}

func buildSessionWhere[Q psql.Filterable](cols sessionColumns) sessionWhere[Q] {
	return sessionWhere[Q]{
		ID:        psql.Where[Q, string](cols.ID),
		UserID:    psql.Where[Q, ulid.ULID](cols.UserID),
		IPAddress: psql.WhereNull[Q, string](cols.IPAddress),
		UserAgent: psql.WhereNull[Q, string](cols.UserAgent),
		ExpiredAt: psql.Where[Q, time.Time](cols.ExpiredAt),
	}
}

var SessionErrors = &sessionErrors{
	ErrUniqueSessionsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "sessions",
		columns: []string{"id"},
		s:       "sessions_pkey",
	},
}

type sessionErrors struct {
	ErrUniqueSessionsPkey *UniqueConstraintError
}

// SessionSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type SessionSetter struct {
	ID        omit.Val[string]     `db:"id,pk" json:"id"`
	UserID    omit.Val[ulid.ULID]  `db:"user_id" json:"user_id"`
	IPAddress omitnull.Val[string] `db:"ip_address" json:"ip_address"`
	UserAgent omitnull.Val[string] `db:"user_agent" json:"user_agent"`
	ExpiredAt omit.Val[time.Time]  `db:"expired_at" json:"expired_at"`
}

func (s SessionSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsSet() {
		vals = append(vals, "id")
	}
	if s.UserID.IsSet() {
		vals = append(vals, "user_id")
	}
	if !s.IPAddress.IsUnset() {
		vals = append(vals, "ip_address")
	}
	if !s.UserAgent.IsUnset() {
		vals = append(vals, "user_agent")
	}
	if s.ExpiredAt.IsSet() {
		vals = append(vals, "expired_at")
	}
	return vals
}

func (s SessionSetter) Overwrite(t *Session) {
	if s.ID.IsSet() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsSet() {
		t.UserID = s.UserID.MustGet()
	}
	if !s.IPAddress.IsUnset() {
		t.IPAddress = s.IPAddress.MustGetNull()
	}
	if !s.UserAgent.IsUnset() {
		t.UserAgent = s.UserAgent.MustGetNull()
	}
	if s.ExpiredAt.IsSet() {
		t.ExpiredAt = s.ExpiredAt.MustGet()
	}
}

func (s *SessionSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Sessions.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 5)
		if s.ID.IsSet() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsSet() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if !s.IPAddress.IsUnset() {
			vals[2] = psql.Arg(s.IPAddress.MustGetNull())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.UserAgent.IsUnset() {
			vals[3] = psql.Arg(s.UserAgent.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.ExpiredAt.IsSet() {
			vals[4] = psql.Arg(s.ExpiredAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s SessionSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s SessionSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsSet() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsSet() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if !s.IPAddress.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "ip_address")...),
			psql.Arg(s.IPAddress),
		}})
	}

	if !s.UserAgent.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_agent")...),
			psql.Arg(s.UserAgent),
		}})
	}

	if s.ExpiredAt.IsSet() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "expired_at")...),
			psql.Arg(s.ExpiredAt),
		}})
	}

	return exprs
}

// FindSession retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindSession(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Session, error) {
	if len(cols) == 0 {
		return Sessions.Query(
			SelectWhere.Sessions.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return Sessions.Query(
		SelectWhere.Sessions.ID.EQ(IDPK),
		sm.Columns(Sessions.Columns().Only(cols...)),
	).One(ctx, exec)
}

// SessionExists checks the presence of a single record by primary key
func SessionExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Sessions.Query(
		SelectWhere.Sessions.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Session is retrieved from the database
func (o *Session) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Sessions.AfterSelectHooks.RunHooks(ctx, exec, SessionSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Sessions.AfterInsertHooks.RunHooks(ctx, exec, SessionSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Sessions.AfterUpdateHooks.RunHooks(ctx, exec, SessionSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Sessions.AfterDeleteHooks.RunHooks(ctx, exec, SessionSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Session
func (o *Session) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Session) pkEQ() dialect.Expression {
	return psql.Quote("sessions", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Session
func (o *Session) Update(ctx context.Context, exec bob.Executor, s *SessionSetter) error {
	v, err := Sessions.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Session record with an executor
func (o *Session) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Sessions.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Session using the executor
func (o *Session) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Sessions.Query(
		SelectWhere.Sessions.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after SessionSlice is retrieved from the database
func (o SessionSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Sessions.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Sessions.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Sessions.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Sessions.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o SessionSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("sessions", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o SessionSlice) copyMatchingRows(from ...*Session) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o SessionSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Sessions.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Session:
				o.copyMatchingRows(retrieved)
			case []*Session:
				o.copyMatchingRows(retrieved...)
			case SessionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Session or a slice of Session
				// then run the AfterUpdateHooks on the slice
				_, err = Sessions.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o SessionSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Sessions.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Session:
				o.copyMatchingRows(retrieved)
			case []*Session:
				o.copyMatchingRows(retrieved...)
			case SessionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Session or a slice of Session
				// then run the AfterDeleteHooks on the slice
				_, err = Sessions.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o SessionSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals SessionSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Sessions.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o SessionSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Sessions.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o SessionSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Sessions.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type sessionJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j sessionJoins[Q]) aliasedAs(alias string) sessionJoins[Q] {
	return buildSessionJoins[Q](buildSessionColumns(alias), j.typ)
}

func buildSessionJoins[Q dialect.Joinable](cols sessionColumns, typ string) sessionJoins[Q] {
	return sessionJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: UserColumns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}

// User starts a query for related objects on users
func (o *Session) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(UserColumns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os SessionSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[ulid.ULID], len(os))
	for i, o := range os {
		pkUserID[i] = o.UserID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "bytea[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(UserColumns.ID).OP("IN", PKArgExpr)),
	)...)
}

func (o *Session) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("session cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Sessions = SessionSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("session has no relationship %q", name)
	}
}

type sessionPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildSessionPreloader() sessionPreloader {
	return sessionPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](orm.Relationship{
				Name: "User",
				Sides: []orm.RelSide{
					{
						From: TableNames.Sessions,
						To:   TableNames.Users,
						FromColumns: []string{
							ColumnNames.Sessions.UserID,
						},
						ToColumns: []string{
							ColumnNames.Users.ID,
						},
					},
				},
			}, Users.Columns().Names(), opts...)
		},
	}
}

type sessionThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildSessionThenLoader[Q orm.Loadable]() sessionThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return sessionThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the session's User into the .R struct
func (o *Session) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Sessions = SessionSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the session's User into the .R struct
func (os SessionSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range users {
			if o.UserID != rel.ID {
				continue
			}

			rel.R.Sessions = append(rel.R.Sessions, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

func attachSessionUser0(ctx context.Context, exec bob.Executor, count int, session0 *Session, user1 *User) (*Session, error) {
	setter := &SessionSetter{
		UserID: omit.From(user1.ID),
	}

	err := session0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachSessionUser0: %w", err)
	}

	return session0, nil
}

func (session0 *Session) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachSessionUser0(ctx, exec, 1, session0, user1)
	if err != nil {
		return err
	}

	session0.R.User = user1

	user1.R.Sessions = append(user1.R.Sessions, session0)

	return nil
}

func (session0 *Session) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachSessionUser0(ctx, exec, 1, session0, user1)
	if err != nil {
		return err
	}

	session0.R.User = user1

	user1.R.Sessions = append(user1.R.Sessions, session0)

	return nil
}
