services:
  database:
    container_name: database
    image: postgres:17-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements
volumes:
  dbdata: